Insert into ALUNO (COD_MAT,NOME,IDADE,DATA_NASC,SEXO,NOME_MAE,NOME_PAI,TURMA) values ('89582','JOSÉ FERREIRA','18',to_date('10/08/02','DD/MM/RR'),'M','MARIA JOSÉ',null,'3º ANO');
Insert into ALUNO (COD_MAT,NOME,IDADE,DATA_NASC,SEXO,NOME_MAE,NOME_PAI,TURMA) values ('53287','ANA MARIA BRANDÃO','17',to_date('09/12/02','DD/MM/RR'),'F','ANTONIA SILVA','CARLOS BRANDÃO','3º ANO');
Insert into ALUNO (COD_MAT,NOME,IDADE,DATA_NASC,SEXO,NOME_MAE,NOME_PAI,TURMA) values ('98563','MARCOS VIANA PRADO','19',to_date('22/01/01','DD/MM/RR'),'M','CLEIDE VIANA','PAULO PRADO','3º ANO');
Insert into ALUNO (COD_MAT,NOME,IDADE,DATA_NASC,SEXO,NOME_MAE,NOME_PAI,TURMA) values ('14235','FERNANDA OLIVEIRA','16',to_date('18/11/03','DD/MM/RR'),'F','MARIA OLIVEIRA',null,'2º ANO');
